name: New Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run Build
        run: npm run build

      - name: Build Failure Notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            **Build Failed!**
            Commit that caused the failure:
            ```
            ${{ github.sha }}
            $(git log -1 --pretty=format:"%s")
            ```
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    needs: build_and_test
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4

      - name: Check for skip in commit messages
        id: check_skip
        env:
          COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ' ') }}
        run: |
          echo "Commit messages: $COMMIT_MESSAGES"
          if [[ "$COMMIT_MESSAGES" == *"#skip"* ]]; then
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
        if: ${{ env.skip != 'true' }}

      - run: npm run build
        if: ${{ env.skip != 'true' }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ env.skip != 'true' }}

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: ${{ env.skip != 'true' }}

      - run: curl --fail https://full-stack-open-pokedex-billowing-forest-165.fly.dev/health
        if: ${{ env.skip != 'true' }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_TYPE: patch
        if: ${{ env.skip != 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Deployment Success Notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Deployment Successful!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
